# 如果您是一名开发者，建议阅读以下内容。如果不是开发者，可以忽略这部分内容。
# 在开发中，将【config.example.yaml】复制一份，改成【config.yaml】

#io context并发线程数
threads: 4
# 服务器基础配置(Basic server configuration)
server:
  # 服务器监听地址和端口(Server listening address and port)
  ip: 0.0.0.0
  port: 8000
  # 认证配置
  auth:
    # 是否启用认证
    enabled: false
    # 设备的token，可以在编译固件的环节，写入你自己定义的token
    # 固件上的token和以下的token如果能对应，才能连接本服务端
    tokens:
      - token: "your-token1" # 设备1的token
        name: "your-device-name1"  # 设备1标识
      - token: "your-token2"  # 设备2的token
        name: "your-device-name2" # 设备2标识
        
log:
  # 设置日志等级：INFO、DEBUG
  log_level: INFO
  # 设置日志路径
  log_dir: tmp
  # 设置日志文件
  log_file: "server.log"

welcome:
  type: hello
  transport: websocket
  audio_params:
    sample_rate: 24000
prompt: |
  你是一个叫小智/小志的台湾女孩，说话机车，声音好听，习惯简短表达，爱用网络梗。
  请注意，要像一个人一样说话，请不要回复表情符号、代码、和xml标签。
  当前时间是:{date_time}，现在我正在和你进行语音聊天，我们开始吧。
  如果用户希望结束对话，请在最后说“拜拜”或“再见”。

# 没有语音输入多久后断开连接(秒)，默认2分钟，即120秒
close_connection_no_voice_time: 120

CMD_exit:
  - "退出"
  - "关闭"
  - "拜拜"
  - "再见"

# 具体处理时选择的模块(The module selected for specific processing)
selected_module:
  ASR: Paraformer
  VAD: SileroVAD
  # 将根据配置名称对应的type调用实际的LLM适配器
  LLM: ChatGLMLLM
  # TTS将根据配置名称对应的type调用实际的TTS适配器
  TTS: EdgeTTS

ASR:
  Paraformer:
    #使用命令:funasr-export ++model=paraformer-zh-streaming ++quantize=true  导出onnx模型，导出的目录填到下面去
    model_dir: funasr的paraformer online模型目录
    quantize: true #使用量化模型
    thread_num: 4
  BytedanceASRV2:
    appid: 你的火山引擎语音合成服务appid
    access_token: 你的火山引擎语音合成服务access_token
    cluster: volcengine_input_common
VAD:
  SileroVAD:
    threshold: 0.5
    model_path: models/silero_vad.onnx
    min_silence_duration_ms: 700  # 如果说话停顿比较长，可以把这个值设置大一些

LLM:
  ChatGLMLLM:
    # glm-4-flash 是免费的，但是还是需要注册填写api_key的
    # 可在这里找到你的api key https://bigmodel.cn/usercenter/proj-mgmt/apikeys
    type: openai
    model_name: glm-4-flash
    url: https://open.bigmodel.cn/api/paas/v4/
    api_key: 你的chat-glm api key
  DifyLLM:
    # 建议使用本地部署的dify接口，国内部分区域访问dify公有云接口可能会受限
    # 如果使用DifyLLM，配置文件里prompt(提示词)是无效的，需要在dify控制台设置提示词
    base_url: https://api.dify.cn/v1
    api_key: 你的DifyLLM api key
  CozeLLMV3:
    bot_id: 你的bot_id
    user_id: 你的user_id
    personal_access_token: 你的coze个人令牌
TTS:
  # 当前支持的type为edge、doubao，可自行适配
  EdgeTTS:
    # 定义TTS API类型,EdgeTTS支持的是24000采样率，需要将welcom.audio_params.sample_rate设置为24000
    voice: zh-CN-XiaoxiaoNeural
  BytedanceTTSV3:
    voice: zh_female_wanwanxiaohe_moon_bigtts
    appid: 你的火山引擎语音合成服务appid
    access_token: 你的火山引擎语音合成服务access_token